apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acs-agents
resources:
  - namespace.yaml
  - acs-policy-configmap.yaml
  - deployment.yaml
  - service.yaml
  - peer-authentication.yaml
  - destination-rule.yaml
