apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: acs-agents
  labels:
    app.kubernetes.io/part-of: acs-sidecar-reference
spec:
  mtls:
    mode: STRICT
